### ISSUE TITLE
Add data file

### ISSUE THREAD

**Issue by oxrc** [oxrc/itstep_jscript_1614#13]
Add a file with interests + users data as 2 separate objects. The file will provide us with the structured data that we will use in our vue.js app.

Single interest JSON representation example: `{"id": 1, "description": "Books"}`
Single user JSON representation example: `{"id": 1, "firstName": "Andrei", "lastName": "Munteanu", "age": 20, "phone": 79897897, "active": 1, "interests": [{"id": 1, "description": "Books"},{"id": 2, "description": "Movies"}]}`

The generated file must contain 30 different interests and 150 unique users and be located in main directory with the name `data.js`

**Comment by xpycmuk** [comment]
It will be better to represent list of interest in user JSON representation as an Array of IDs and not as Array of Objects

`{"id": 1, "firstName": "Andrei", "lastName": "Munteanu", "age": 20, "phone": 79897897, "active": 1, "interests": [1, 2, ....., n]}`

**Comment by oxrc** [comment]
Update :: The data file should also contain a couple of username/passwords:

Single user info: `{"username": "radu", "password": "radu"}`.

This info will be used on login page (we will change it to a proper server architecture later in time, when we'll start working on the server).

**Comment by oxrc** [comment]
Closed in #15 .
