### ISSUE TITLE
Choose overall style for project

### ISSUE THREAD

**Issue by Lurkomorie** [oxrc/itstep_jscript_1614#6]
Choose and present an overall style for project. Minimalistic

**Comment by TimShustov** [comment]
![bgmain](https://user-images.githubusercontent.com/32590491/32566218-2f7bd516-c4c0-11e7-942a-e08bb0bec26e.jpg)

**Comment by TimShustov** [comment]
http://ui-cloud.com/apollo-gui-pack/
+- style
http://css3buttongenerator.com/ button creator

**Comment by TimShustov** [comment]
https://www.google.com/search?q=background+for+app&rlz=1C1PRFI_enMD711MD716&tbm=isch&source=lnt&tbs=isz:l&sa=X&ved=0ahUKEwiznrLOv6_XAhXQIuwKHcuTDyIQpwUIGw&biw=1920&bih=974&dpr=1#imgdii=Nz0oRv1TnQB-KM:&imgrc=qlF1aOioyx79jM:

**Comment by Lurkomorie** [comment]
Changing because of bad resolution
![d3a1aeac2317bde3c12eda1f8ce4f805](https://user-images.githubusercontent.com/26333528/32572065-23586e68-c4d2-11e7-84ca-d0117609067b.jpg)

**Comment by Lurkomorie** [comment]
new Info
color for Buttons: #368BB4,
Hover Buttons: #2E7094,
focus on inputs: #46ABE1

**Comment by Lurkomorie** [comment]
for additional information on our design write in telegram group

**Comment by oxrc** [comment]
I need an HTML page with all elements on it that are colored according to the colors/design you suggested. It should be in `/design/` directory, as `index.html`. All styles and scripts for it should be in the same directory - `/design/` .

**Comment by TimShustov** [comment]
#66b3ff

**Comment by oxrc** [comment]
Styles are already present in `design` folder.

**Comment by TimShustov** [comment]
![image](https://user-images.githubusercontent.com/32590491/33185693-284db740-d08d-11e7-92e5-af0f65dbc567.png)
